pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - 'author=pulanski'
      - 'check-success=coverage_for_pull_requests'
      # https://docs.mergify.com/conditions/#about-status-checks
    actions:
      merge:
        method: merge

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge

  - name: automatic merge for Snyk pull requests
    conditions:
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success~=^security/snyk
    actions:
      merge:
        method: merge
