#!/bin/sh

# shellcheck source=.husky/_/husky.sh
. "$(dirname "$0")/_/husky.sh"

nx affected --target=test --codeCoverage
# nx affected --target=e2e
# nx affected --target=version
# nx affected --target=build
npx lint-staged
